//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSessionCoursA15.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADRESSE()
        {
            this.IMMEUBLEs = new HashSet<IMMEUBLE>();
        }
    
        public string codePostal { get; set; }
        public int numero { get; set; }
        public string rue { get; set; }
        public string localite { get; set; }
        public string ville { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMMEUBLE> IMMEUBLEs { get; set; }
    }
}
