//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSessionCoursA15.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIL
    {
        public string ImmeubleID { get; set; }
        public int LocataireID { get; set; }
        public System.DateTime Date_Debut { get; set; }
        public Nullable<System.DateTime> Date_Fin { get; set; }
        public Nullable<int> BIENID { get; set; }
    
        public virtual BIENIMMOBILIER BIENIMMOBILIER { get; set; }
        public virtual Locataire Locataire { get; set; }
    }
}
