//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSessionCoursA15.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMEUBLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMMEUBLE()
        {
            this.BIENIMMOBILIERs = new HashSet<BIENIMMOBILIER>();
            this.IMAGEs = new HashSet<IMAGE>();
        }
    
        public string ImmeubleID { get; set; }
        public string codePostal { get; set; }
        public Nullable<int> numero { get; set; }
        public string Type_Immeuble { get; set; }
    
        public virtual ADRESSE ADRESSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENIMMOBILIER> BIENIMMOBILIERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGE> IMAGEs { get; set; }
    }
}
