//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSessionCoursA15.Models.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProjetImmobilierEntities : DbContext
    {
        public ProjetImmobilierEntities()
            : base("name=ProjetImmobilierEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADRESSE> ADRESSEs { get; set; }
        public virtual DbSet<Annonce> Annonces { get; set; }
        public virtual DbSet<BAIL> BAILs { get; set; }
        public virtual DbSet<BIENIMMOBILIER> BIENIMMOBILIERs { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<IMAGE> IMAGEs { get; set; }
        public virtual DbSet<IMMEUBLE> IMMEUBLEs { get; set; }
        public virtual DbSet<Locataire> Locataires { get; set; }
        public virtual DbSet<utilisateur> utilisateurs { get; set; }
        public virtual DbSet<Visite> Visites { get; set; }
    
        public virtual ObjectResult<getListeAnnoncee_Result> getListeAnnoncee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListeAnnoncee_Result>("getListeAnnoncee");
        }
    }
}
