//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSessionCoursA15.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public int id { get; set; }
        public string nomUtilisateur { get; set; }
        public string courriel { get; set; }
        public string motDePasse { get; set; }
        public Nullable<int> photo { get; set; }
        public string EmployeID { get; set; }
        public Nullable<int> LocataireID { get; set; }
        public string clientID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Locataire Locataire { get; set; }
    }
}
