//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSessionCoursA15.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visite
    {
        public System.DateTime DateVisite { get; set; }
        public string clientID { get; set; }
        public Nullable<int> BIENID { get; set; }
        public string ImmeubleID { get; set; }
        public string EmployeID { get; set; }
        public string nom { get; set; }
    
        public virtual BIENIMMOBILIER BIENIMMOBILIER { get; set; }
        public virtual Client Client { get; set; }
        public virtual Employe Employe { get; set; }
    }
}
